# Generated by Django 3.0 on 2022-02-18 09:41

from django.db import migrations
from oc_lettings_site import models
from profiles.models import Profile
from django.contrib.auth.models import User


def populate(apps, shema_editor):
    profiles = models.Profile.objects.all()
    for profile in profiles:
        user = User.objects.get(id=profile.user.id)
        Profile(
            user=user,
            favorite_city=profile.favorite_city
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
