# Generated by Django 3.0 on 2022-02-18 09:23

from django.db import migrations
from oc_lettings_site import models
from lettings.models import Address, Letting


def populate(apps, shema_editor):
    addresses = models.Address.objects.all()
    for address in addresses:
        Address(
            number=address.number,
            street=address.street,
            city=address.city,
            state=address.state,
            zip_code=address.zip_code,
            country_iso_code=address.country_iso_code
        ).save()
    
    lettings = models.Letting.objects.all()
    for letting in lettings:
        letting_address = Address.objects.get(id=letting.address.id)
        Letting(
            title=letting.title,
            address=letting_address
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
