version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-test:
    docker:
      - image: likhardcore/oc-lettings
    steps:
      - checkout
      - run: python3 -m venv env
      - run: pip install -r requirements.txt
      - run: source env/bin/activate && flake8
      - run: source env/bin/activate && pytest
  containerise:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build --tag ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run: docker push ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - build-and-test
      - containerise:
          requires:
            - build-and-test
      - deploy:
          requires:
            - containerise